/**
 * config.js  —  Atıksız Çiftlik: Döngüsel Yaşam Simülasyonu
 */

export const CONFIG = Object.freeze({
    grid: { width: 14, height: 14 },
    tile: { w: 64, h: 32 },
    voxel: { perTile: 4, size: 16, height: 16 },
    camera: { minZoom: 0.5, maxZoom: 3.0, defaultZoom: 1.4 },
    layers: Object.freeze({ TERRAIN: 0, WATER: 1, OBJECT: 2 }),
    storageKey: 'atıksız-çiftlik.save.v1',

    palette: Object.freeze({
        // Yeşiller
        grass:         '#7db85e',
        grassDark:     '#5a8c40',
        grassLight:    '#9ecc7e',
        meadow:        '#a8c97a',
        meadowDark:    '#7aaa4a',
        leaf:          '#4a8a3e',
        leafDark:      '#2d5c25',
        leafLight:     '#6eb05e',
        darkGreen:     '#2d5a1a',
        // Toprak
        soil:          '#7a5230',
        soilDark:      '#5a3a1e',
        soilLight:     '#9e6e44',
        soilRich:      '#8a4c20',
        mud:           '#6a4828',
        clay:          '#b8764a',
        clayDark:      '#8a5030',
        // Saman / Tahıl
        straw:         '#e2c65a',
        strawDark:     '#bea030',
        strawLight:    '#f0dc84',
        wheat:         '#d4a830',
        wheatDark:     '#a87c1e',
        hay:           '#c8b048',
        // Ahşap
        wood:          '#a0703a',
        woodDark:      '#6c4820',
        woodLight:     '#c89050',
        bark:          '#7a5028',
        barkLight:     '#9e6a3a',
        plank:         '#b8844a',
        plankDark:     '#8a5e2e',
        // Taş
        stone:         '#b0a892',
        stoneDark:     '#8a8068',
        stoneLight:    '#ccc4ae',
        fieldStone:    '#a09878',
        concrete:      '#c4bca8',
        // Çatı / Ahır
        roof:          '#c44e2e',
        roofDark:      '#9a3318',
        roofLight:     '#dc6e4a',
        barn:          '#a83020',
        barnDark:      '#7a1e10',
        barnLight:     '#c84a38',
        // Beyaz / Badana
        white:         '#f4f0e8',
        whiteShadow:   '#ddd8cc',
        whiteDeep:     '#c8c2b2',
        cream:         '#f8f0d8',
        // Bitkiler
        tomato:        '#dc3c2c',
        tomatoDark:    '#aa2018',
        tomatoLight:   '#f05a44',
        apple:         '#d44020',
        appleGreen:    '#5a8c30',
        appleLeaf:     '#4a7020',
        vegGreen:      '#4a9044',
        vegDark:       '#307030',
        vegLeaf:       '#68b056',
        carrot:        '#e07828',
        corn:          '#e8c040',
        sunflower:     '#f4c820',
        sunflowerDark: '#c8980a',
        // Sürdürülebilirlik
        compostBrown:  '#6a4018',
        compostRich:   '#8a5820',
        solarBlue:     '#2a6aaa',
        solarDark:     '#1a4a7a',
        solarLight:    '#4a8aca',
        solarCell:     '#3a7aba',
        plastic:       '#5a9ec8',
        plasticLight:  '#7abcdc',
        metalGray:     '#8a9aaa',
        metalDark:     '#5a6a78',
        metalLight:    '#aabbc8',
        recycleGreen:  '#2a9a5a',
        recycleDark:   '#1a7040',
        waterTank:     '#4a7ea8',
        waterTankDark: '#2a5c80',
        waterBlue:     '#5aacdc',
        waterDeep:     '#3a8abc',
        waterShine:    '#8ad0f0',
        // Hayvanlar
        cowBody:       '#f0ead8',
        cowSpot:       '#2a2420',
        cowNose:       '#e0a888',
        cowHoof:       '#3a2818',
        chickenBody:   '#f0d870',
        chickenRed:    '#dc3030',
        sheepBody:     '#ece8e0',
        sheepFace:     '#8a7868',
        sheepLeg:      '#6a5848',
        dogBrown:      '#b87848',
        dogDark:       '#7a4c28',
        dogSnout:      '#c89060',
        // Çit / Çevre
        fence:         '#9a7048',
        fenceDark:     '#6e4c28',
        fencePost:     '#7a5430',
        path:          '#c8b888',
        pathDark:      '#a89c70',
        pathLight:     '#dcd0a4',
        sand:          '#ddc898',
        sandDark:      '#b8a070',
        // Su / Gölet
        pondBlue:      '#5ab0d8',
        pondDeep:      '#3a88aa',
        pondShine:     '#88cce8',
        // Genel
        gold:          '#e0b840',
        iron:          '#3a3830',
        ironLight:     '#5a5850',
        flame:         '#ffc050',
        // Eski sistem uyumluluğu için
        cobalt:        '#2a6aaa',
        cobaltLight:   '#4a8aca',
        cobaltDeep:    '#1a4a7a',
        skyBlue:       '#5aacdc',
        sea:           '#5ab0d8',
        seaDeep:       '#3a88aa',
        seaShine:      '#88cce8',
        seaWall:       '#b0a892',
        cypress:       '#4a8a3e',
        cypressDark:   '#2d5c25',
        cypressLight:  '#6eb05e',
        olive:         '#7a9460',
        oliveDark:     '#5a7448',
        oliveLight:    '#9bb37e',
        bougain:       '#dc3c2c',
        bougainDark:   '#aa2018',
        bougainLight:  '#f05a44',
        agave:         '#a8c97a',
        agaveDark:     '#7aaa4a',
        dryGrass:      '#e2c65a',
        terracotta:    '#c44e2e',
        terraLight:    '#dc6e4a',
        terraDark:     '#9a3318',
        flower:        '#f4c820',
        flowerYellow:  '#f4c820',
        flowerWhite:   '#f8f0d8',
        crop:          '#9ecc7e',
        cropDark:      '#5a8c40',
        glass:         '#d8f0f8',
    }),
});
